---
- name: OpenShift Cluster Health Check
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Run cluster health module
      ocp_cluster_health:
        host: "https://api.ocp4.linuxp.local:6443"
        username: "wahba"
        password: "admin"
        verify_ssl: false
      register: health_result
      failed_when: health_result.degraded_operators | length > 0
    - name: Display results
      debug:
        var: health_result
